#kong-gw Admin
GET http://localhost:8001/services
Accept: application/json

###

#kong-test
GET http://localhost:8000/gists
Accept: application/json

###

#To test more rapidly, the cache can be deleted by calling the Admin API:
DELETE http://localhost:8001/proxy-cache

###

#api key test
GET http://localhost:8000/gists
Accept: application/json
apikey: test-header-key

###

#consumer ip-restriction test - consumer
#allow: 192.0.0.1/8, 172.0.0.1/8
GET http://localhost:8000/gists
Accept: application/json
apikey: test-header-key

###

#consumer ip-restriction test - consumer1
#allow: 172.0.0.1/8
GET http://localhost:8000/gists
Accept: application/json
apikey: test-header-key1

###

#consumer ip-restriction test - consumer2
#allow: 192.0.0.1/8
GET http://localhost:8000/gists
Accept: application/json
apikey: test-header-key2

###

#consumer ip-restriction test - consumer3
#disallow: 192.0.0.1/8, allow: 172.0.0.1/8
GET http://localhost:8000/gists
Accept: application/json
apikey: test-header-key3

###

#consumer ip-restriction test - consumer4
#allow: 192.0.0.1/8, disallow: 172.0.0.1/8
GET http://localhost:8000/gists
Accept: application/json
apikey: test-header-key4

###

# curl -X POST http://localhost:8001/consumers/consumer3/plugins
#    --data "name=ip-restriction"
#
#    --data "config.allow=192.0.0.1/8"
POST http://localhost:8001/consumers/consumer3/plugins
Content-Type: application/x-www-form-urlencoded

name=ip-restriction&config.allow=192.0.0.1/8

###
